version: "3.7"
services:

  nginx:
    build:
      context: ./app/docker/development
      dockerfile: nginx.docker
    volumes:
      - ./app:/app
    depends_on:
      - php-fpm
    ports:
      - "8080:80"

  php-fpm:
    build:
      context: ./app/docker/development
      dockerfile: php-fpm.docker
    volumes:
      - ./app:/app
    depends_on:
      - postgres

  php-cli:
    build:
      context: ./app/docker/development
      dockerfile: php-cli.docker
    volumes:
      - ./app:/app
      - composer:/root/.composer/cache
    depends_on:
      - postgres

  postgres:
    image: postgres:12.1-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: db
    ports:
      - "54321:5432"

volumes:
  postgres:
  composer:
